# This workflow will be triggered on every merge to the prod, int, and dev branches 

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Validation only runs if an AsyncAPI spec file is present in the commit

# To get started, configure the following in your repos secrets https://docs.github.com/en/actions/security-guides/encrypted-secrets
# SOLACE_CLOUD_TOKEN
## The following confluend cloud keys should have a global access type
# TF_VAR_confluent_cloud_api_key
# TF_VAR_confluent_cloud_api_secret
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# WORKFLOW_PAT: Personal Access Token token for the destination repo for authentication. See more here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
## Note: The PAT should have workflow access enabled

# Important: Update the SOLACE_MESSAGING_SERVICE environment variable to the environment name on Solace Pubsub+ Event Portal to associate a branch to an environment

name: Provision the confluent cluster
on:
  push: 
    branches: [ prod ]

env:
  SOLACE_MESSAGING_SERVICE: PROD-Kafka
  SOLACE_CLOUD_TOKEN: ${{ secrets.SOLACE_CLOUD_TOKEN }}
  TF_VAR_confluent_cloud_api_key: ${{ secrets.TF_VAR_confluent_cloud_api_key }}
  TF_VAR_confluent_cloud_api_secret: ${{ secrets.TF_VAR_confluent_cloud_api_secret }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
          
      - name: Checkout Current Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # Get all files in commit
      - id: changed-files
        uses: tj-actions/changed-files@v39
        with:
            separator: ","
    
      - name: List all modified files
        run: |
          IFS=$',' read -a MODIFIED_FILES_ARRAY <<< "${{ steps.changed-files.outputs.all_modified_files }}"
          asyncapiFiles=()
          for file in "${MODIFIED_FILES_ARRAY[@]}"
              do
                if [[ ( ${file} == *.yaml ) || ( ${file} == *.yml ) ||  (${file} == *.json )]]
                then
                  asyncapiFiles+=("$file")
                  echo "ASYNCAPI_FILE_PATH=${file}" >> $GITHUB_ENV
                fi
              done
            unset IFS
            if [ ${#asyncapiFiles[@]} -eq 0 ]; then
              echo "Cancel workflow. No asyncapi spec file found to promote!"
              echo "CANCEL_WORKFLOW=true" >> $GITHUB_ENV
            fi
        shell:
          bash

      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.CANCEL_WORKFLOW == 'true'
        uses: andymckay/cancel-action@0.3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}

      # Spec file found in commit
      - name: Checkout terraform configuration repo
        uses: actions/checkout@v4
        with:
          repository: TamimiGitHub/solace-terraform-provisioning
          path: terraform
      
      - name: Install dependencies
        run: |
          cd terraform
          npm install

      - name: Promote application 
        run: |
          cd terraform
          npm run promote -- -f "../$ASYNCAPI_FILE_PATH" -mes $SOLACE_MESSAGING_SERVICE -d

  provision:
      needs: promote 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout terraform configuration repo
          uses: actions/checkout@v4
          with:
            repository: TamimiGitHub/solace-terraform-provisioning
        
        - name: Install dependencies
          run: npm install

        - name: run provision commands
          run: SOLACE_MESSAGING_SERVICE=$SOLACE_MESSAGING_SERVICE npm run provision
